AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys Plex onto AWS using EC2, S3, and other services"
Parameters:
  PlexProjectId:
    Type: "String"
    Description: >-
      Unique project id for your Plex installation. Must be at least 12
      characters long.
    MinLength: 12
  PlexVpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "VPC where Plex will be deployed."
Resources:
  PlexS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${PlexProjectId}-plex-media-bucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: "aws/s3"
      AccessControl: "Private"
      VersioningConfiguration:
        Status: "Suspended"
      LifecycleConfiguration:
        Rules:
        - Id: !Sub "${PlexProjectId}MediaBucketRule"
          Status: "Enabled"
          NoncurrentVersionExpirationInDays: 90
          Transitions:
          - StorageClass: "STANDARD_IA"
            TransitionInDays: 60
